### DISCUSSION TITLE
What are the dimensions of a good testing dataset?

### DISCUSSION THREAD

**Discussion by satra** [nmind/hackathon2021#16] [Ideas]
- Motion and other artifacts
- Different types of fieldmaps or none
- Well known task paradigms

let's try to determine the different dimensions that we should have.

@oesteban @mgxd

**Comment by gkiar** [comment]
- is cross species data available?

For structural imaging/brain extraction:
- ground truth segmentations

**Comment by gkiar** [comment]
For determining the grade of a dataset/benchmark, which would help with interpretability, we could create an exhaustive list of dimensions and a rubric for how to determine the standard based on which subset of them are checked

**Comment by arueter1** [comment]
Hey Audrey, thought you might be a good person to be a part of this conversation. @hough129

**Comment by gkiar** [comment]
Here is a first pass at a list or properties we want to cover in the dataset:

```yaml
Developmental Status:
Species:
  - State/Task
  - Contrast agents
Clinical Population:
Evaluation Standard:
Data quality:
  - Motion
  - Artifacts
Modality:
  - Acquisition protocol type:
    - Scanner
    - Magnet strength
  - Data quantity
Ancillary data availability:
```

It's possible this list could be enhanced with other BIDS-esque metadata, too...
